---

name: shadetree

services:
  api:
    image: shadetree-api:latest
    build:
      context: ./api
      dockerfile: Dockerfile.development
      args:
        UID: 1000
        GID: 1000
    depends_on:
      - database
    environment:
      RAILS_ENV: development
      DATABASE_HOST: database
      DATABASE_USER: postgres
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: api
        target: /rails
  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: shadetree_development
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data

volumes:
  postgres_data:
